modLoader="javafml"
loaderVersion="[3,)"
license="MIT License"

[[mods]]
    modId="command_structures"
    version="${version}"
    displayName="Command Structure Mod"
    logoFile="commandstructures.png"
    logoBlur=false
    authors="TelepathicGrunt"
    description='''
    Spawn structures by command'''

[[mixins]]
    config = "command_structures.mixins.json"

[[dependencies.command_structures]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"